java_proto_library(
    name = "kafkaexactlyonce_java_proto",
    deps = [":kafkaexactlyonce_proto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "kafkaexactlyonce_proto",
    srcs = ["kafkaexactlyonce.proto"]
)