java_library(
    name = "utils",
    srcs = glob(["*.java"]),
    deps = [
        "@org_slf4j_slf4j_api//jar",
        "@org_apache_curator_curator_framework//jar",
        "@org_apache_curator_curator_client//jar",
        "@org_apache_curator_curator_test//jar",
        "@org_apache_kafka_kafka_2_11//jar",
        "@org_apache_kafka_kafka_clients//jar",
        "@net_sf_jopt_simple_jopt_simple//jar",
        "@com_google_guava_guava//jar",
    ]
)
